[[redirects]]
  from = "/single-iconlibrary-sidebar-left"
  to = "/single-iconlibrary-sidebar-left.html"
  status = 302
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/single-starterkit-sidebar-left"
  to = "/single-starterkit-sidebar-left.html"
  status = 302
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/single-pnhlogo-sidebar-left"
  to = "/single-pnhlogo-sidebar-left.html"
  status = 302
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/single-iconlibrary-sidebar-left"
  to = "/.netlify/functions/redirect"
  status = 302
  force = true

[[redirects]]
  from = "/single-starterkit-sidebar-left"
  to = "/.netlify/functions/redirect"
  status = 302
  force = true

[[redirects]]
  from = "/single-pnhlogo-sidebar-left"
  to = "/.netlify/functions/redirect"  
  status = 302
  force = true

[functions]
  directory = "functions"
